# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    sync_code_signing(git_url: "git@github.com:eugenpirogoff/signing_wifi_to_qr.git", type: "appstore")
    build_app(workspace: "Wifi to QR.xcworkspace", scheme: "Wifi to QR", include_bitcode: true, export_method: "app-store")
    upload_to_app_store
  end
end
